baseURL = "https://theninthparadise.github.io/"
languageCode = "en-us"
title = "The Ninth Paradise"
theme = "archie"

[params]
  mode = "light"  # 可选: "light", "dark", "auto"
  subtitle = "我的 Hugo 个人网站"
  brand = "Ninth Paradise"
  favicon = "/favicon.ico"

  # 是否启用社交链接
  useCDN = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[social]
  github = "theninthparadise"
  linkedin = "your-linkedin-username"
  twitter = "your-twitter-handle"

